added effects on hovering buttons
COPS-IITBHU/hackalog-frontend pull request #165
Opened 2021-10-23 12:35 UTC by NerdyLucifer

**Fixes**

Fixes #164 

**Description**

**Checklist:**

-   [x] I have read the contribution guidelines in the repository.
-   [x] My branch is up-to-date with upstream branch.
-   [x] My pull request has a descriptive title (not a vague title like "Update package.json").
-   [x] My code follows the established code style of the repository.
-   [x] I have tried running the project locally and verified that there are no visible errors.

2021-10-30 20:43 UTC, shubhanshu02 requested changes
Last few fixes to merge the PR.

2021-10-30 20:43 UTC, shubhanshu02 commented on pages/hackathon/[slug]/index.tsx
> +                    content={`"Register for ${hackathon.title} at COPS Hackalog,`}
Remove `"` and `,`

2021-10-30 20:43 UTC, shubhanshu02 commented on pages/hackathons.tsx
> +import { table } from "console"
Unused. Remove

2021-10-30 20:43 UTC, shubhanshu02 commented on pages/hackathons.tsx
> +                <title>{`${selectedTab} Hackathons | COPS Hackalog`}</title>
The lowercase `selectedTab` looks a bit awkward. As a simple fix, we can change the keys from 'ongoing' to "Ongoing".

2021-10-30 20:43 UTC, shubhanshu02 commented on pages/hackathons.tsx
> +    return { tab }
It will be better to support the case when no query is given by the user.

```ts
return { tab: tab ?? "Ongoing" }
```

2021-10-30 20:43 UTC, shubhanshu02 commented on components/Header/Header.tsx
> +                            <Link href="/hackathons?tab=ongoing">
Revert this back.

2021-10-30 20:43 UTC, shubhanshu02 commented on pages/hackathons.tsx
> +                <title>{`${selectedTab} Hackathons | COPS Hackalog`}</title>
Change event key from `ongoing` to `Ongoing`. Similarly for `completed` and `upcoming`.
```jsx
<Nav.Link eventKey="ongoing">Ongoing</Nav.Link>
```
```jsx
<Tab.Pane eventKey="ongoing">....</Tab.Pane>
```

2021-10-31 06:35 UTC, shubhanshu02 approved these changes
Nothing else from my side. Just take a pull as there's a merge conflict.

2021-10-31 07:15 UTC, NerdyLucifer commented
@shubhanshu02  I have resolved the conflicts

2021-10-31 07:23 UTC, shubhanshu02 commented
I guess you removed your own changes (the CSS classes from the nav buttons)

2021-10-31 07:26 UTC, NerdyLucifer commented
> I guess you removed your own changes (the CSS classes from the nav buttons)

yeah, i have committed them again

2021-10-31 07:40 UTC, shubhanshu02 commented
For the Google Sign-in button, the background color on hover makes it not appealing. Remove the color for that button

2021-10-31 07:58 UTC, shubhanshu02 approved these changes
Great work @NerdyLucifer. Thanks :clinking_glasses:

2021-10-31 07:59 UTC, merged

2021-10-31 08:05 UTC, NerdyLucifer commented
> Great work @NerdyLucifer. Thanks 🥂

Thanks  🙌