Issue of presence of unused variables resolved
COPS-IITBHU/hackalog-frontend pull request #86
Opened 2021-08-13 16:35 UTC by garimavs

**Fixes**

Fixes #[issue number] by @[issue author]

**Description**

**Checklist:**

-   [ ] I have read the contribution guidelines in the repository.
-   [ ] My branch is up-to-date with upstream branch.
-   [ ] My pull request has a descriptive title (not a vague title like "Update package.json").
-   [ ] My code follows the established code style of the repository.
-   [ ] I have tried running the project locally and verified that there are no visible errors.

2021-08-13 17:53 UTC, shubhanshu02 requested changes
Just a few changed, I'd say. Also, run `npm run format` at the end before committing the changes.

2021-08-13 17:53 UTC, shubhanshu02 commented on pages/hackathon/[slug]/index.js
> +// line 738
Remove this line

2021-08-13 17:53 UTC, shubhanshu02 commented on pages/hackathon/[slug]/index.js
> +                            alt="Error 404"
Not part of this issue

2021-08-14 07:14 UTC, garimavs commented on pages/hackathon/[slug]/index.js
> +// line 738
the requested change is applied

2021-08-14 07:15 UTC, garimavs commented on pages/hackathon/[slug]/index.js
> +                            alt="Error 404"
the requested change is applied

2021-08-14 10:07 UTC, shubhanshu02 approved these changes
LGTM. Thanks @garimavs.

2021-08-14 10:08 UTC, merged