Rename project tab to Teams
COPS-IITBHU/hackalog-frontend pull request #95
Opened 2021-09-06 12:06 UTC by PuneetDabral

**Fixes**

Fixes #[issue number] by @[issue author]

**Description**

**Checklist:**

-   [ ] I have read the contribution guidelines in the repository.
-   [ ] My branch is up-to-date with upstream branch.
-   [ ] My pull request has a descriptive title (not a vague title like "Update package.json").
-   [ ] My code follows the established code style of the repository.
-   [ ] I have tried running the project locally and verified that there are no visible errors.

2021-09-06 12:12 UTC, PuneetDabral commented
thanku sir  for giving me this opportunity please review these changes and merge this ...

2021-09-06 13:09 UTC, shubhanshu02 requested changes

2021-09-06 13:09 UTC, shubhanshu02 commented on pages/profile/[username].js
> +                                                Teams
Other than simply changing the tab name, the `eventKey` attribute must be changed. And similarly to the Tabs where this event key is being accessed.

2021-09-06 13:11 UTC, shubhanshu02 commented
Also, do fill the pull request description with the appropriate issue number and other details.

2021-09-06 15:42 UTC, PuneetDabral commented
now its ok ...sorry sir for extra commit actually i am in beginner phase ...so i need all of your support so i can learn more & more

2021-09-06 18:01 UTC, shubhanshu02 requested changes
Looks good to me :+1:. 

To resolve the merge conflict, can you rebase your branch with the main branch of this repository? The steps would be:

```
git remote add upstream https://github.com/COPS-IITBHU/hackalog-frontend.git
git pull upstream main --rebase
git push origin Puneet -f
```

2021-09-06 18:03 UTC, PuneetDabral commented
wait  sir i will ...!!

2021-09-06 18:08 UTC, PuneetDabral commented
sir it will show error .....unable to access 'https://github.com/PuneetDabral/hackalog-frontend.git/': Could not resolve host: github.com

2021-09-06 18:13 UTC, shubhanshu02 commented
If I'm not wrong the last command must be giving this error, right?

2021-09-06 18:13 UTC, PuneetDabral commented
now check it sir ...

2021-09-06 18:14 UTC, shubhanshu02 approved these changes
Ya, now it's fine. Thanks.

Btw, don't call me 'sir'. I'm still a student. :wink:

2021-09-06 18:15 UTC, merged

2021-09-06 18:17 UTC, PuneetDabral commented
thank you very much i learn alot from you ..can you give me more (good first issue) so i can learn more ....thanku once again

2021-09-06 18:53 UTC, shubhanshu02 commented
I'll see and let you know tomorrow. Thanks

2021-09-07 04:47 UTC, PuneetDabral commented
ok sir i am waiting you can give me. more good first issue of beginner level from this or may be other repo....

2021-09-08 11:39 UTC, PuneetDabral commented
sir any good first issue?..so i can learn more from you...

2021-09-08 20:20 UTC, shubhanshu02 commented
Sorry, was really busy in the last two days. How about #69?

2021-09-09 05:05 UTC, PuneetDabral commented
its ok sir.....basically sir. i am beginner so learn react. if you help me or teach me . i will definitely solve this issue and some other also  ...

2021-09-12 07:25 UTC, shubhanshu02 commented
You can refer to the documentation of the Effect hook (https://reactjs.org/docs/hooks-effect.html)